### ISSUE TITLE
Will added Conan/VCPKG Support ?

### ISSUE THREAD

**Issue by meftunca** [jplflyer/cpp-faker#1]
Will added Conan/VCPKG Support ?

**Comment by jplflyer** [comment]
Good question. I'm not sure what's involved. I just skimmed a page that explained how to use Conan for building, but that particular page didn't explain how to add support to make a package conan-able. I'd be more than happy to accept pull requests for it.

**Comment by meftunca** [comment]
If I have time I'll pack it for conan
